version: '2'
services:
  ap:
    image: redmine
    ports:
      - 3001:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME : redmine
      REDMINE_DB_PASSWORD: redmine
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - file-vol:/usr/src/redmine/files
#      - ./plugins:/usr/src/redmine/plugins
#      - ./themes:/usr/src/redmine/public/themes
    restart: always

  db:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
      - db-vol:/var/lib/mysql
    restart: always
volumes:
  db-vol:
  file-vol:

