version: '2'

services:
  db:
    image: mongo
    volumes:
      - db-vol:/data/db
      - dump-vol:/dump
    command: mongod --smallfiles
    restart: always

  ap:
    image: rocketchat/rocket.chat
    environment:
      - MONGO_URL=mongodb://db:27017/rocketchat
      - ROOT_URL=http://localhost:3000
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 3000:3000
    restart: always

volumes:
  db-vol:
  dump-vol:

